
###
POST http://localhost:6060/order/create
content-type: application/json

{
"order": {
    "locationId": 'LQP8GSV27SQ1K',
    "referenceId": 'PLATE_XXXX123456',
    "lineItems": [
        {
            "name": 'Traffic Violation 0001',
            "quantity": '1',
            "note": 'OK',
            "itemType": 'ITEM',
            "basePriceMoney": {
            "amount": 30,
            "currency": 'USD',
            }
        },
        {
            "name": 'Traffic Violation 0001',
            "quantity": '1',
            "note": 'OK',
            "itemType": 'ITEM',
            "basePriceMoney": {
            "amount": 30,
            "currency": 'USD',
            }
        }
    ]
}
}
###

POST http://localhost:6060/payment/create
content-type: application/json
{
    
"orderId": "3VjJfw4hvxOohnmOzMfm8PwfE9YZY"

}