@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTNkZGUwY2U0ZjIwZDU4ODQ2ZTdmNiIsImVtYWlsIjoibmV3TWFpbFdpdGhJbmZvUmVmcmVzaFVwZGF0ZS5jb20iLCJpYXQiOjE2NDAxMDIzNTUsImV4cCI6MTY0MDEwMzI1NX0.aalVXVe9LK4yK4tVxR3dggg-upr2-WYCpF9DjlzSP88
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTNkZGUwY2U0ZjIwZDU4ODQ2ZTdmNiIsImVtYWlsIjoibmV3TWFpbFdpdGhJbmZvUmVmcmVzaFVwZGF0ZS5jb20iLCJpYXQiOjE2NDAxMDIzNTUsImV4cCI6MTY3MTY1OTk1NX0.IC2F0oBussrH8lDMMm4VVGaCHjEGyVfh3tQi5i-z6FA


###
GET http://localhost:6060/user/
Authorization: Token {{token}}
###
GET http://localhost:6060/user/info/
Authorization: Token {{token}}

###
GET http://localhost:6060/auth/
Authorization: Basic newMailWithInfoRefreshUpdate.com:@hashedPassword
###
POST http://localhost:6060/auth/refresh
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}

###
POST http://localhost:6060/auth/logout
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}

###
POST http://localhost:6060/user/logout

###
POST http://localhost:6060/user/create
Content-Type: application/json

{
    "email": "newMailWithInfoRefreshUpdate.com",
    "password": "@hashedPassword",
    "info": {"value1":1,"value2":2}
}

// DATA

###
GET http://localhost:6060/data/
Authorization: Token {{token}}

### ADD SINGLE
POST http://localhost:6060/data/
Authorization: Token {{token}}
Content-Type: application/json

{
    "data": {
        "newData": "Testing new Data",
        "newData2": "Testing new Data2"
    }
}

### ADD SINGLE 1
POST http://localhost:6060/data/
Authorization: Token {{token}}
Content-Type: application/json

{
    "data": {
        "newData": "Arr2",
        "newData2": "Arr223"
    }
}

### ADD UPDATE
PUT http://localhost:6060/data/
Authorization: Token {{token}}
Content-Type: application/json

{
    "id": "61c1fa4372dcd2a3790fe5c6",
    "data": {
        "newData": "Update1",
        "newData2": "Update2"
    }
}

### DELETE
DELETE http://localhost:6060/data/
Authorization: Token {{token}}
Content-Type: application/json

{
    "id": "61c1fa4372dcd2a3790fe5c6"
}


