
###
GET http://localhost:6060/user/

###
GET http://localhost:6060/user/info/

###
GET http://localhost:6060/auth/
Authorization: Basic email46789@email:123

###
POST http://localhost:6060/user/logout

###
POST http://localhost:6060/user/create
Content-Type: application/json

{
    "email": "email46789@email",
    "password": "123",
    "info": {"value1":1,"value2":2}
}

###
GET http://localhost:6060/data/

###
GET http://localhost:6060/data/123

###
DELETE http://localhost:6060/data/

###
DELETE http://localhost:6060/data/123

###
POST http://localhost:6060/data/

###
PUT http://localhost:6060/data/123

