@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTRhNDNiNTMxY2JkMmRmYzgwNTczZCIsImVtYWlsIjoibmV3TWFpbFdpdGhJbmZvUmVmcmVzaFVwZGF0ZS5jb20iLCJpYXQiOjE2MzcxMzMyNTUsImV4cCI6MTYzNzEzNDE1NX0.0kptl9NtnRlpelWkE5rs8zrXCfVdUaZEqnbTmTG-MW0
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTRhNDNiNTMxY2JkMmRmYzgwNTczZCIsImVtYWlsIjoibmV3TWFpbFdpdGhJbmZvUmVmcmVzaFVwZGF0ZS5jb20iLCJpYXQiOjE2MzcxMzMyNTUsImV4cCI6MTY2ODY5MDg1NX0.6r09evjksZy_DlebXJRyCg6zXG-3aFgWqDgJJ27DJAA


###
GET http://localhost:6060/user/
Authorization: Token {{token}}
###
GET http://localhost:6060/user/info/
Authorization: Token {{token}}

###
GET http://localhost:6060/auth/
Authorization: Basic newMailWithInfoRefreshUpdate.com:@hashedPassword
###
POST http://localhost:6060/auth/refresh
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}

###
POST http://localhost:6060/auth/logout
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}

###
POST http://localhost:6060/user/logout

###
POST http://localhost:6060/user/create
Content-Type: application/json

{
    "email": "newMailWithInfoRefreshUpdate.com",
    "password": "@hashedPassword",
    "info": {"value1":1,"value2":2}
}

// DATA

###
GET http://localhost:6060/data/
Authorization: Token {{token}}

###
POST http://localhost:6060/data/
Authorization: Token {{token}}
Content-Type: application/json

{
    "newData": "Testing new Data",
    "newData2": "Testing new Data2"
}

